==== STATE of this repo: Generally working, but being updated frequently. Still pretty brittle due to lots of hardcoded parameters.


==== Need to fix:
* Need to be able to disable NFS server and NFS StorageClass from within variables.tf file
* Need to be able to pass helm server info into admin node from within variables.tf file
** Could also use cluster-deploy.sh to set keys/values in a file, b64 encode that file then sed it into the admin node cloud-init file
* Found that cluster-deploy.sh is dependent on appropriate entries for the KVM user and hosts in .ssh/config file
* Remove hardcoded references to RMT server - DONE

==== Dependencies:
* Must use RMT server as Helm server 
* Currently only deploys one cluster per KVM host and cannot deploy a cluster across hosts

==== Deployment overview:
. Install Terraform
. Install the terraform-libvirt-provider
. Clone the skuba repo: `git clone https://github.com/SUSE/skuba.git`
. Clone this repo: `git clone https://github.com/alexarnoldy/Unified_CaaSP_Terraform.git`
. Copy the contents of this repo into the skuba/ci/infra/libvirt directory: `cp -pr Unified_CaaSP_Terraform/* skuba/ci/infra/libvirt/`
. (Optional) Create a soft link to the libvirt directory to make it easier to access: `ln -s skuba/ci/infra/libvirt/ libvirt`
. Append extra-variables-tf file to the variable.tf file: `cp -p variables.tf variables.tf.orig && cat extra-variables-tf >> variables.tf`
* NOTE: The default deployment provides an NFS StorageClass with an NFS share from the admin node. If this is desired, be sure to add `nsf-client` to the "packages" variable in variables.tf
. Run `terraform init`
. Update the infrastructre directory with a file for each KVM host (the file name is the FQDN of the host) containing the KVM user and SSH public key
. Create an images directory: `mkdir images/`
. Download a SLES15 SP1 JeOS cloud image (i.e. SLES15-SP1-JeOS.x86_64-15.1-OpenStack-Cloud-QU*.qcow2) into the images/ directory from https://downloads.suse.com
. Update terraform.tfvars file with the specifics for your environment including, at a minimum: 
* The `image_uri`, i.e. `image_uri = "images/SLES15-SP1-JeOS.x86_64-15.1-OpenStack-Cloud-QU2.qcow2"`
* The CaaS Platform registration code or the RMT server name (i.e. rmt_server_name = "rmt.example.com")
. Update the cluster-deploy.sh script variables with the specifics for your environment
. Ensure the local user has passwordless ssh to each KVM host as its KVM user 
. Ensure the KVM user is in the libvirt group and has passwordless sudo privileges
//. Start ssh-agent with the ssh key that provides passwordless ssh access
. Deploy with ./cluster-deploy.sh
.. Destroy with ./cluster-destroy.sh


// vim: set syntax=asciidoc:

